//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public string admission_no { get; set; }
        public string course { get; set; }
        public Nullable<int> amount_paid { get; set; }
    }
}
